name: Build and Lint

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  check-skippable:
    continue-on-error: true
    runs-on: ubuntu-22.04
    # Minimum permissions required by skip-duplicate-actions
    permissions:
      actions: write
      contents: read
    outputs:
      skippable: ${{ steps.check.outputs.should_skip }}
    steps:
      - id: check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1

  build-lint:
    name: Build and Lint
    needs: check-skippable
    if: needs.check-skippable.outputs.skippable != 'true'

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          show-progress: false
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          standalone: false

      - name: Setup Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm build

      - run: pnpm lint
